#!/usr/bin/env node
/**
 * Copy Supabase keys from backend/supabase/.env → apps/web/.env.local
 * Does not print secret values.
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const src = resolve(root, "backend/supabase/.env");
const dest = resolve(root, "apps/web/.env.local");

if (!existsSync(src)) {
  console.error("Missing backend/supabase/.env — copy .env.example and fill in keys first.");
  process.exit(1);
}

function parseEnv(content) {
  const map = {};
  for (const line of content.split("\n")) {
    const t = line.trim();
    if (!t || t.startsWith("#")) continue;
    const i = t.indexOf("=");
    if (i === -1) continue;
    map[t.slice(0, i).trim()] = t.slice(i + 1).trim();
  }
  return map;
}

const env = parseEnv(readFileSync(src, "utf8"));
const url = env.SUPABASE_URL;
const anon = env.SUPABASE_ANON_KEY;
const worker = env.WORKER_URL ?? env.NEXT_PUBLIC_WORKER_URL ?? "";

if (!url || !anon || url.includes("your-project")) {
  console.error("backend/supabase/.env missing SUPABASE_URL or SUPABASE_ANON_KEY");
  process.exit(1);
}

const out = `# Auto-generated by scripts/wire-env.mjs — do not commit
NEXT_PUBLIC_SUPABASE_URL=${url}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${anon}
NEXT_PUBLIC_WORKER_URL=${worker}
`;

writeFileSync(dest, out);
console.log("✅ Wrote apps/web/.env.local from backend/supabase/.env");
console.log("   Restart: pnpm dev:web");
